apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: {{MODEL_NAME}}
  namespace: {{NAMESPACE}}
  labels:
    app.kubernetes.io/name: {{MODEL_NAME}}
    app.kubernetes.io/managed-by: model-manager{{EXTRA_LABELS}}
spec:
  predictor:
{{NRI_ANNOTATIONS}}    minReplicas: {{REPLICAS}}
    maxReplicas: {{REPLICAS}}
    model:
      modelFormat:
        name: {{MODEL_FORMAT}}
      storageUri: {{MODEL_URI}}
      runtime: {{RUNTIME_NAME}}
      args: {{ARGS}}
      env: {{ENV}}
      resources:
        requests:
          cpu: {{CPU}}
          memory: {{MEMORY}}
        limits:
          cpu: {{CPU}}
          memory: {{MEMORY}}
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
          - ALL
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
{{AFFINITY}}
